### ISSUE TITLE
Chapter10: remenber_me.py JSONDecodeError

### ISSUE THREAD

**Issue by KawaiiAsh** [ehmatthes/pcc#105]
If `username.json` is empty. then will get
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

So we should add `json.JSONDecodeError` in `def get_stored_username()`
```python
def get_stored_username():
    filename = 'username.json'
    try:
        with open(filename,'r',encoding='UTF-8') as file_object:
            username = json.load(file_object)
    except (FileNotFoundError,json.JSONDecodeError):
        return None
    else:
        return username
```
That is how it is working.

**Comment by ehmatthes** [comment]
This is the code for the first edition of Python Crash Course, which has been out of print since 2019. The code for this book is well out of date. I will archive this repo shortly, to help clarify that.

The third edition came out in January of this year, and is fully up to date. Resources for the new edition are here: [https://ehmatthes.github.io/pcc_3e/](https://ehmatthes.github.io/pcc_3e/)
