### ISSUE TITLE
Chapter 18 models.py TypeError on ForeignKey() Instance

### ISSUE THREAD

**Issue by morgansamson** [ehmatthes/pcc#44]
I'm not sure if this is a recent change / change to Django since the book was published, but while following the exercises in Chapter 18 on Django2.0, I got the `TypeError: __init__() missing 1 required positional argument:` error when I was working on Chapter 18's portion of adding the `Entry` class to the models.py file. I even tried copy-pasting exactly the code you have in Github in case I just had a typo or so, but I still got the error.

The error occurred when creating the `topic` attribute in the Entry class definition because the instance created with `models.ForeignKey()` only had 1 argument (`Topic`) and did not have an argument for `on_delete`. 

- Portion of Code erroring out: https://github.com/ehmatthes/pcc/blob/master/chapter_18/learning_logs/models.py#L14
- Django documentation regarding `ForeignKey` arguments: https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.ForeignKey
- Django documentation regarding `on_delete`: https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.ForeignKey.on_delete

When I included an argument for `on_delete`, the error resolved. However, I wasn't 100% sure yet which value I should use for the `on_delete` argument because I am still so early on in the Learning Log project. I settled for `on_delete=models.PROTECT` for now because based on the project, I felt as if we wouldn't want all the entries to get deleted simply because a Topic got deleted and also because `on_delete=models.SET_NULL` ended up with its own errors. I'll research that more.

**Comment by ehmatthes** [comment]
Hi @morgansamson, there were some more significant changes in Django 2.0 that affect this project. These changes are great; they make Django a little easier to use for the most part.

Here's the [full set of updates](http://ehmatthes.github.io/pcc/chapter_18/README.html#updates) for the project. If you run into any issues, please feel free to reach out through email (ehmatthes@gmail), or twitter [@ehmatthes](https://twitter.com/ehmatthes).

You'll want to use `on_delete=models.CASCADE`; that was the default in previous versions of Django. That means that when a topic is deleted, all of the entries associated with that topic will also be deleted. That's the behavior we want, otherwise we'd have entries in our database that aren't associated with any topics.
  
Edit: Just to clarify, I would not expect you to figure out the best setting for `on_delete` in your first Django project! The best approach to deleting information in a web app is a rich topic. You certainly want to give users the ability to completely delete their data. But you also don't want people to accidentally delete all their data, and when they ask you to restore it you can't help them. There are ways to flag data as inactive, and then you can set policies where inactive data is deleted after it's been inactive for a set period of time. What's most important in a real-world app is making sure your approach to deletion of data is transparent to your users.

In this project, the admin is the only place you can delete data. The setting for `on_delete` will affect any deletion you do through the admin, and for this project `CASCADE` is an appropriate setting.

**Comment by morgansamson** [comment]
@ehmatthes  - Sorry this is delayed (holidays and work got crazy!) but thank you for the update and answering my question, especially clarifying why you recommend the `models.CASCADE` on_delete value! I completely missed the chapter-by-chapter updates in the repo, so thanks!

**Comment by ehmatthes** [comment]
Sure thing!
